### ISSUE TITLE
Click a day to open a new page

### ISSUE THREAD

**Issue by woottonn** [zabuto/calendar#1]
Hi there,

Really enjoying this calendar, and the modal popup integration. 

I have multiple events that fall on one date - but at the minute can only get one event to show in the modal.

Is it possible to change it so that days with multiple events open a new page rather than a modal window?

Best regards :)

Nick

**Comment by CamaroMan** [comment]
hi - not sure what is happening and if i ucked someting up - but in firebug im getting multiple instances of my loop, ie - each "date" is producing multiple divs, alll prefixed like so:

<div id="zabuto_calendar_1vgq_2015-04-15_modal" class="modal">...
<div id="zabuto_calendar_1z2a_2015-04-15_modal" class="modal">...
<div id="zabuto_calendar_5eg_2015-04-15_modal" class="modal">...

these are all for the same date - but not allowing me to do in-modal js operations due to multiples.. is this me having messed something up?

Ive modified the cal php file to add in different $data into each modal window for the modals. the data pulls thru fine - except I am getting these odd id's for each date - 

is there a loop in the js file? if i find anything ill holler - could well be something i did wrong.. thanks

**Comment by CamaroMan** [comment]
hi - is there a way to update the calendar every x seconds? ie i have linked it to a booking system, and it only displays the changes if i refresh the page.. even clicking to a new month and back doesnt update it. I am loading this through a bootstrap modal. Otherwise thanks for a cool little app - 

:p
